base: /
dependencies:
  - typo3/theme-camino
languages:
  -
    title: Deutsch
    enabled: true
    locale: de-DE
    hreflang: de-DE
    base: /
    websiteTitle: Camino
    navigationTitle: Deutsch
    fallbackType: strict
    fallbacks: '0'
    flag: de
    languageId: 1
  -
    title: English
    enabled: true
    locale: en-US
    hreflang: en-US
    base: /en/
    websiteTitle: Camino
    navigationTitle: English
    flag: global
    languageId: 0
rootPageId: 1
websiteTitle: Camino
